### ISSUE TITLE
Hello World fails

### ISSUE THREAD

**Issue by rdebath** [yukas/brainfuck#1]
This program should print out `Hello World!`

``` bf
>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by yukas** [comment]
Now it does: https://github.com/yukas/brainfuck/blob/master/test/hello_world_test.rb

**Comment by rdebath** [comment]
The published repository still does not run the "Hello World" in this issue. The `[` instruction does not follow your README.

**Comment by yukas** [comment]
Changed `[` instruction implementation. Thank you for notice!

`>++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.>->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.`

code seems using cell values below zero which is against this particular implementation:

- Incrementing 255 or decrementing 0 results in a fatal error

**Comment by rdebath** [comment]
Okay, this variant doesn't have that test. The loops still aren't working right.
```bf
>++++++++[-<+++++++++>]<.>[][<-]>+>    ++>++>+++[>[->+++<<+++>]<<]>-----.
> >+++..+++.>-.<< [>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.
```

**Comment by yukas** [comment]
Fixed the loops, made the last example work, finally! Thank you, @rdebath!
